version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "1.9.x" # oldest supported branch
    schedule:
      interval: "weekly"
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: monthly
    target-branch: "1.9.x"
    milestone: 136
    ignore:
      # only upgrade patch versions
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: monthly
    target-branch: "1.10.x"
    milestone: 159
    ignore:
      # only upgrade patch versions
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: monthly
    target-branch: "1.11.x"
    milestone: 206
    ignore:
      # only upgrade patch versions
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: monthly
    target-branch: "main"
    milestone: 185
    ignore:
      # upgrade minor and patch versions on main
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 10
